highlighter: pygments
permalink: /:title/
production_url: http://dlion.it
name: DLion ~ Blog
description_name: Domenico Luciani
description_blog: DLion ~ Blog
url: http://dlion.it
image_url: /public/img/posts
future: false
safe: true
lsi: false
timezone: Europe/Rome
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post"
    values:
      layout: "post"

