markdown: redcarpet
highlighter: pygments
permalink: /:title/
production_url: http://dlion.it
name: DLion ~ Blog
description: Domenico Luciani | DLion ~ Blog
url: http://dlion.it
image_url: /public/img/posts
paginate: 10
paginate_path: "/page/:num"
future: false
safe: true
timezone: Europe/Rome
gems:
  - jekyll-mentions
  - jemoji
defaults:
    -
        scope:
            path: "_posts/"
        values:
            layout: "post"
