markdown: kramdown
highlighter: pygments
permalink: /:title/
production_url: dlion.it
name: DLion ~ Blog
description_name: Domenico Luciani
description_blog: DLion ~ Blog
url: dlion.it
github: DLion
twitter: dlion92
linkedin: dlion
disqus: dlion
author: Domenico Luciani
gplus: +DomenicoLeoneLuciani
image_url: /public/img/posts
future: false
safe: true
lsi: false
timezone: Europe/Rome
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "posts"

gems:
      - jekyll-feed
